require("custom.configs.harpoon")
require("custom.configs.undotree")
require("custom.configs.fugitive")
require("custom.configs.nvim-tree")
require("custom.configs.neogit")
require("custom.configs.lualine")
require("custom.configs.prettier")
require("custom.configs.flutter-tools")
require("custom.configs.todo-comments")
require("custom.configs.refactoring")
require("custom.configs.vimtex")
require("custom.configs.kanagawa")
vim.cmd.colorscheme 'nordic'
-- require("custom.configs.monokai-pro")
-- require("custom.configs.gruvbox")
--
-- require("custom.configs.tokyonight")
