require("custom.configs.harpoon")
require("custom.configs.undotree")
require("custom.configs.nvim-tree")
require("custom.configs.neogit")
require("custom.configs.lualine")
require("custom.configs.todo-comments")
require("custom.configs.refactoring")
require("custom.configs.vimtex")
-- require("custom.configs.nordic")
